# Generated by Django 6.0.6 on 2026-06-17 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='buku',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='nama_peminjam',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='petugas',
        ),
        migrations.AddField(
            model_name='buku',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buku',
            name='tahun_terbit',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buku',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penerbit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='pengarang',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buku',
            name='rak',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='buku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpus.buku'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status',
            field=models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='Dipinjam', max_length=20),
        ),
        migrations.AlterModelTable(
            name='buku',
            table=None,
        ),
        migrations.AlterModelTable(
            name='peminjaman',
            table=None,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='siswa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perpus.siswa'),
            preserve_default=False,
        ),
    ]
